### ISSUE TITLE
Can pusher get its hostname info from Kubernetes?

### ISSUE THREAD

**Issue by pboothe** [m-lab/pusher#33]
One less configuration option would be nice...

Could possibly be done via the downward API.  This would represent a continuation of the work done in #18 .

**Comment by pboothe** [comment]
The pod does get its name from k8s. Pusher becoming k8s-aware is not worth doing when compared with the minimal difficulty of adding:
```yaml
        env:
        - name: MLAB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
to the daemonset.  In particular, pusher needs to be simple, because its reliability comes (in part) from its simplicity.
